### ISSUE TITLE
Japanese Faction

### ISSUE THREAD

**Issue by R34Fletto** [PhoebeIV/OpenRA-OW#15]
Japanese Faction

pretty much just using the Rise of The Reds Japan mod as the base, need to actually get the mod working to figure out finer details

Not sure if mod already has subfactions but can maybe do

Mecha General
Psionics General
Plasma General

Laser colour is LIGHT BLUE (Upgrades to PURPLE)

--Buildings--

Construction Yard
Barracks
Supply Center
War Factory (Mecha Bay)
Powerplant - Sacrifice Reactor (30 seconds unlimited power but lose structure in a violent explosion)
Airfield
Dockyard (Imperial Docks)
Mainframe - Techbuilding
Psychic Data Center - Techbuilding
Psionic Decimator - Super Weapon - release a wave of psionic energy on a location

-- Defense --

Laser base - Firebase but with laser gun, air and land
Transformer Base - Takes on the weapon of the vehicle that enters [1300]
Balloon Sentry - Balloon mounted railgun that can move, can be deployed to anchor and increase firerate

-- Vehicles --

Harvester - Can travel through water
Sudden Transport - Invisible APC that can travel through water
Tsunami Tank - Medium Tank, can travel through water - plasma gun
Datenshi - Anti air vehicle - armed with a laser crossbow

-- Mechs --

Executioner - Heavy Melee mecha - Strong vs Vehicles and Strutures, weak vs Infantry and Aircraft
Dominatrix - Support mech unit, can disable structures and units at a long range
Mecha Tengu - Fires a machine gun at ground units, tranforms into jet to target airunits
Striker VX -
Mecha Transformer - Exosuits for infantry, takes on the weapon of its passenger

-- Aircraft --

Jet Tengu - Opposite of Mecha Techu
Kistune
Yousei
Kaminari
Tantou

-- Naval --

Kappa Gunboat
Naginata Cruiser
Shogun Battleship
Genbu Hovercraft

-- Infantry --

Shinobi - Stealth sword DUDE
Imperial Warrior - basic infantry with machine gun (150)
Archer Maiden - Anti-air infantry (Strong vs Infantry, Aircraft, weak vs vehicles) (300)
Tank Buster - plasma launcher (strong vs vehicles, weak vs infantry & aircraft)
Rocket Angel - Flying rocket unit barrage of 8 rockets (Strong vs Vehicles & Infantry, Weak vs aircraft) (450)
War Horse - Archer horse
Matsui Yuriko - hero unit, uses psionics to destroy enemies, can read minds to reveal enemy locations, can release a psionic pulse
Bio Engineer - Support unit, heals infantry and create infantry, attack enemy infantry to collect DNA samples (make him make zombies or something idfk)
Titan - Genetically mutated soldier that is stronk (Strong vs Infantry & Tanks, weak vs Structures)

SKY EMPRESS

-- PLUGIN/UPGRADE --

Vehicle Repair Data - Nearby vehicles at production facilities will repair
Dual Tank Barrels - Upgrade Tsunami tanks to have double cannons
Integrated Base Systems - Reduce cost of structures by 15%
Laser Base Medkits - Heals nearby units 
Arrow Homing Systems - Increase arrow speed and lifetime
Remote Assembly - Allows Mecha Tengu & Striker VX to be made on airfield queue. Allows assembly of Tsunami Tank, Sudden Transport, Mecha Tengu & Striker VX on Docks
Focused Lasers - Upgrades weapons for Laser Base, Hiroshima Artillery, Dominatrix and Tantou
Ore Driller - Delivers an Oredrill to extract new resources
Rocket Angel Cryo-Stream - upgrades rockets to freeze units, slowing movement speed (maybe on multiple stacks on infantry it freezes them completely?)
Explosive Arrows - does this need explaining?
Super Heated Plasma - Upgrades weapons for Tankbuster, Raiju, Executioner, Balloon Sentry and Shogun Battleship
DNA Research - Unlocks Titan, Bioengineer and DNA Health Research
DNA Health Research - increases HP of all infantry by 100%
DNA Stamina Research -  Increases infantry vision (33%), range (33%), damage (25%), firerate (10%) and movement speed (75%)
DNA Cloning Research - Reduce soldier cost by 25%, Yuriko can be cloned

-- Support Powers --

Tenshi Squad - Paradrops of 3 Veteran angels
Vile Curse - Debuffs enemy units
Antimatter bomb - drops antimatter bombs
Spacewarp - Transports vehicles through a warp hole (instantly kills any nearby infantry)
Clairvoyance - Reveal An area
Final Squadron - Kamikaze planes
Shinobi Ambush - ambush of 3 Shinobi warriors
Divine Intervention - Airdrop of a plasma bomb at a target (unpredictable results)

**Comment by PhoebeIV** [comment]
Completed, currently receiving occasional fine tuning, as with everything in the mod
