### ISSUE TITLE
Hero Units.

### ISSUE THREAD

**Issue by Tumbrawolf** [PhoebeIV/OpenRA-OW#4]
Will start with just medi hero.

Can level up 3-5 times per tier

Each level has upgrades available.
Level 1 and 2 Upgrades carry over between tiers

Level 1: Range. Vision. Speed.
Level 2: Damage. Resistance. Reload.
Level 3: Tier up. Change Class. Special 1(per unit special upgrades)
Level 4: Tier up. Special 2. Change class.
Level 5: Tier up. Change Class.

Some units will not have specials.

Tier Up: keep same unit class but just make it next tier instead of changing the unit.
Class Change: go to next tier and select a new unit

Will put the actual units into their own Yaml files, but keep the core framework a shared Yaml.

**Comment by Tumbrawolf** [comment]
Spawn dummy actor based on upgrade. Each level needs hero to be at that level in correct tier
Spawned dummy holds 2 traits. 1 for the tier/level and a 2nd for what upgrade you built.

Stats and specials: these just hold level and tier as well as grant prereq of what the added bonus is. If you upgrade tier of a unit the special for the following Tier will be disabled.

Tier up: changes based on unit you have active. Kills your unit and allows you to rebuild a new one for free. When new one is produced, it will grant a Prerequisite chain to lock getting a free instant unit again untill next tier. Essentially just skips the class change actor.

Change class: same as Tier up but requires you to pick a new class from the tier. This will just be a research that locks your pick in. Just extra step but same as Tier up.

Level 1: Range. Vision. Speed.
Level 2: Damage. Resistance. Reload.
Level 3: Tier up. Change Class. Special 1(per unit special upgrades)
Level 4: Tier up. Special 2. Change class.
Level 5: Tier up. Change Class.

**Comment by PhoebeIV** [comment]
I think we could mark this as closed since it's been implemented (albeit a little differently)
